<?php
/**
 * ChunkFull
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * WebAPI
 *
 * Access Sponge powered Minecraft servers through a WebAPI  #/ Introduction This is the documentation of the various API routes offered by the WebAPI plugin.  This documentation assumes that you are familiar with the basic concepts of Web API's, such as `GET`, `PUT`, `POST` and `DELETE` methods, request `HEADERS` and `RESPONSE CODES` and `JSON` data.  By default this documentation can be found at http:/localhost:8080 (while your minecraft server is running) and the various routes start with http:/localhost:8080/api/...  As a quick test try reaching the route http:/localhost:8080/api/info (remember that you can only access \"localhost\" routes on the server on which you are running minecraft). This route should show you basic information about your server, like the motd and player count.  #/ Additional data Certain endpoints (such as `/player`, `/entity` and `/tile-entity` have additional properties which are not documented here, because the data depends on the concrete object type (eg. `Sheep` have a wool color, others do not) and on the other plugins/mods that are running on your server which might add additional data.  You can also find more information in the github docs (https:/github.com/Valandur/Web-API/tree/master/docs/DATA.md)
 *
 * OpenAPI spec version: <version>
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;

/**
 * ChunkFull Class Doc Comment
 *
 * @category    Class
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ChunkFull implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'ChunkFull';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'uuid' => 'string',
        'position' => '\Swagger\Client\Model\Vector3',
        'world' => '\Swagger\Client\Model\World',
        'block_min' => '\Swagger\Client\Model\Vector3',
        'block_max' => '\Swagger\Client\Model\Vector3',
        'is_loaded' => 'bool',
        'inhabited_time' => 'float',
        'difficulty_factor' => 'double',
        'difficulty_percentage' => 'double'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerFormats = [
        'uuid' => null,
        'position' => null,
        'world' => null,
        'block_min' => null,
        'block_max' => null,
        'is_loaded' => null,
        'inhabited_time' => 'integer',
        'difficulty_factor' => 'double',
        'difficulty_percentage' => 'double'
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'uuid' => 'uuid',
        'position' => 'position',
        'world' => 'world',
        'block_min' => 'blockMin',
        'block_max' => 'blockMax',
        'is_loaded' => 'isLoaded',
        'inhabited_time' => 'inhabitedTime',
        'difficulty_factor' => 'difficultyFactor',
        'difficulty_percentage' => 'difficultyPercentage'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'uuid' => 'setUuid',
        'position' => 'setPosition',
        'world' => 'setWorld',
        'block_min' => 'setBlockMin',
        'block_max' => 'setBlockMax',
        'is_loaded' => 'setIsLoaded',
        'inhabited_time' => 'setInhabitedTime',
        'difficulty_factor' => 'setDifficultyFactor',
        'difficulty_percentage' => 'setDifficultyPercentage'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'uuid' => 'getUuid',
        'position' => 'getPosition',
        'world' => 'getWorld',
        'block_min' => 'getBlockMin',
        'block_max' => 'getBlockMax',
        'is_loaded' => 'getIsLoaded',
        'inhabited_time' => 'getInhabitedTime',
        'difficulty_factor' => 'getDifficultyFactor',
        'difficulty_percentage' => 'getDifficultyPercentage'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['uuid'] = isset($data['uuid']) ? $data['uuid'] : null;
        $this->container['position'] = isset($data['position']) ? $data['position'] : null;
        $this->container['world'] = isset($data['world']) ? $data['world'] : null;
        $this->container['block_min'] = isset($data['block_min']) ? $data['block_min'] : null;
        $this->container['block_max'] = isset($data['block_max']) ? $data['block_max'] : null;
        $this->container['is_loaded'] = isset($data['is_loaded']) ? $data['is_loaded'] : null;
        $this->container['inhabited_time'] = isset($data['inhabited_time']) ? $data['inhabited_time'] : null;
        $this->container['difficulty_factor'] = isset($data['difficulty_factor']) ? $data['difficulty_factor'] : null;
        $this->container['difficulty_percentage'] = isset($data['difficulty_percentage']) ? $data['difficulty_percentage'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets uuid
     * @return string
     */
    public function getUuid()
    {
        return $this->container['uuid'];
    }

    /**
     * Sets uuid
     * @param string $uuid The unique identifier of the chunk.
     * @return $this
     */
    public function setUuid($uuid)
    {
        $this->container['uuid'] = $uuid;

        return $this;
    }

    /**
     * Gets position
     * @return \Swagger\Client\Model\Vector3
     */
    public function getPosition()
    {
        return $this->container['position'];
    }

    /**
     * Sets position
     * @param \Swagger\Client\Model\Vector3 $position
     * @return $this
     */
    public function setPosition($position)
    {
        $this->container['position'] = $position;

        return $this;
    }

    /**
     * Gets world
     * @return \Swagger\Client\Model\World
     */
    public function getWorld()
    {
        return $this->container['world'];
    }

    /**
     * Sets world
     * @param \Swagger\Client\Model\World $world
     * @return $this
     */
    public function setWorld($world)
    {
        $this->container['world'] = $world;

        return $this;
    }

    /**
     * Gets block_min
     * @return \Swagger\Client\Model\Vector3
     */
    public function getBlockMin()
    {
        return $this->container['block_min'];
    }

    /**
     * Sets block_min
     * @param \Swagger\Client\Model\Vector3 $block_min
     * @return $this
     */
    public function setBlockMin($block_min)
    {
        $this->container['block_min'] = $block_min;

        return $this;
    }

    /**
     * Gets block_max
     * @return \Swagger\Client\Model\Vector3
     */
    public function getBlockMax()
    {
        return $this->container['block_max'];
    }

    /**
     * Sets block_max
     * @param \Swagger\Client\Model\Vector3 $block_max
     * @return $this
     */
    public function setBlockMax($block_max)
    {
        $this->container['block_max'] = $block_max;

        return $this;
    }

    /**
     * Gets is_loaded
     * @return bool
     */
    public function getIsLoaded()
    {
        return $this->container['is_loaded'];
    }

    /**
     * Sets is_loaded
     * @param bool $is_loaded True if the chunk is currently loaded in the world, false otherwise.
     * @return $this
     */
    public function setIsLoaded($is_loaded)
    {
        $this->container['is_loaded'] = $is_loaded;

        return $this;
    }

    /**
     * Gets inhabited_time
     * @return float
     */
    public function getInhabitedTime()
    {
        return $this->container['inhabited_time'];
    }

    /**
     * Sets inhabited_time
     * @param float $inhabited_time The number of ticks a player has been present in this chunk.
     * @return $this
     */
    public function setInhabitedTime($inhabited_time)
    {
        $this->container['inhabited_time'] = $inhabited_time;

        return $this;
    }

    /**
     * Gets difficulty_factor
     * @return double
     */
    public function getDifficultyFactor()
    {
        return $this->container['difficulty_factor'];
    }

    /**
     * Sets difficulty_factor
     * @param double $difficulty_factor Gets the regional difficulty factor for this chunk.
     * @return $this
     */
    public function setDifficultyFactor($difficulty_factor)
    {
        $this->container['difficulty_factor'] = $difficulty_factor;

        return $this;
    }

    /**
     * Gets difficulty_percentage
     * @return double
     */
    public function getDifficultyPercentage()
    {
        return $this->container['difficulty_percentage'];
    }

    /**
     * Sets difficulty_percentage
     * @param double $difficulty_percentage Gets the regional difficulty as a percentage for this chunk.
     * @return $this
     */
    public function setDifficultyPercentage($difficulty_percentage)
    {
        $this->container['difficulty_percentage'] = $difficulty_percentage;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


