<?php
/**
 * CommandResult
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * WebAPI
 *
 * Access Sponge powered Minecraft servers through a WebAPI  #/ Introduction This is the documentation of the various API routes offered by the WebAPI plugin.  This documentation assumes that you are familiar with the basic concepts of Web API's, such as `GET`, `PUT`, `POST` and `DELETE` methods, request `HEADERS` and `RESPONSE CODES` and `JSON` data.  By default this documentation can be found at http:/localhost:8080 (while your minecraft server is running) and the various routes start with http:/localhost:8080/api/...  As a quick test try reaching the route http:/localhost:8080/api/info (remember that you can only access \"localhost\" routes on the server on which you are running minecraft). This route should show you basic information about your server, like the motd and player count.  #/ Additional data Certain endpoints (such as `/player`, `/entity` and `/tile-entity` have additional properties which are not documented here, because the data depends on the concrete object type (eg. `Sheep` have a wool color, others do not) and on the other plugins/mods that are running on your server which might add additional data.  You can also find more information in the github docs (https:/github.com/Valandur/Web-API/tree/master/docs/DATA.md)
 *
 * OpenAPI spec version: <version>
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;

/**
 * CommandResult Class Doc Comment
 *
 * @category    Class
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CommandResult implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'CommandResult';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'affected_blocks' => 'float',
        'affected_entities' => 'float',
        'affected_items' => 'float',
        'query_result' => 'float',
        'success_count' => 'float'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerFormats = [
        'affected_blocks' => null,
        'affected_entities' => null,
        'affected_items' => null,
        'query_result' => null,
        'success_count' => null
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'affected_blocks' => 'affectedBlocks',
        'affected_entities' => 'affectedEntities',
        'affected_items' => 'affectedItems',
        'query_result' => 'queryResult',
        'success_count' => 'successCount'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'affected_blocks' => 'setAffectedBlocks',
        'affected_entities' => 'setAffectedEntities',
        'affected_items' => 'setAffectedItems',
        'query_result' => 'setQueryResult',
        'success_count' => 'setSuccessCount'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'affected_blocks' => 'getAffectedBlocks',
        'affected_entities' => 'getAffectedEntities',
        'affected_items' => 'getAffectedItems',
        'query_result' => 'getQueryResult',
        'success_count' => 'getSuccessCount'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['affected_blocks'] = isset($data['affected_blocks']) ? $data['affected_blocks'] : null;
        $this->container['affected_entities'] = isset($data['affected_entities']) ? $data['affected_entities'] : null;
        $this->container['affected_items'] = isset($data['affected_items']) ? $data['affected_items'] : null;
        $this->container['query_result'] = isset($data['query_result']) ? $data['query_result'] : null;
        $this->container['success_count'] = isset($data['success_count']) ? $data['success_count'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets affected_blocks
     * @return float
     */
    public function getAffectedBlocks()
    {
        return $this->container['affected_blocks'];
    }

    /**
     * Sets affected_blocks
     * @param float $affected_blocks The number of block that were affected.
     * @return $this
     */
    public function setAffectedBlocks($affected_blocks)
    {
        $this->container['affected_blocks'] = $affected_blocks;

        return $this;
    }

    /**
     * Gets affected_entities
     * @return float
     */
    public function getAffectedEntities()
    {
        return $this->container['affected_entities'];
    }

    /**
     * Sets affected_entities
     * @param float $affected_entities The number of entities that were affected.
     * @return $this
     */
    public function setAffectedEntities($affected_entities)
    {
        $this->container['affected_entities'] = $affected_entities;

        return $this;
    }

    /**
     * Gets affected_items
     * @return float
     */
    public function getAffectedItems()
    {
        return $this->container['affected_items'];
    }

    /**
     * Sets affected_items
     * @param float $affected_items The number of items that were affected.
     * @return $this
     */
    public function setAffectedItems($affected_items)
    {
        $this->container['affected_items'] = $affected_items;

        return $this;
    }

    /**
     * Gets query_result
     * @return float
     */
    public function getQueryResult()
    {
        return $this->container['query_result'];
    }

    /**
     * Sets query_result
     * @param float $query_result The query result number.
     * @return $this
     */
    public function setQueryResult($query_result)
    {
        $this->container['query_result'] = $query_result;

        return $this;
    }

    /**
     * Gets success_count
     * @return float
     */
    public function getSuccessCount()
    {
        return $this->container['success_count'];
    }

    /**
     * Sets success_count
     * @param float $success_count The success count.
     * @return $this
     */
    public function setSuccessCount($success_count)
    {
        $this->container['success_count'] = $success_count;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


